#!/bin/bash
 
set -e
 
cat <<-'EOF' > /etc/apt/sources.list
    deb http://kambing.ui.ac.id/raspbian/raspbian/ jessie main contrib non-free rpi
	deb-src http://kambing.ui.ac.id/raspbian/raspbian/ jessie main contrib non-free rpi
	deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi
	deb-src http://mirrrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi
EOF
 
apt-get update
apt-get dist-upgrade -y
apt-get install -y elinks
